nepse_symbols = [
    "ACLBSL",
    "ADBL",
    "AHL",
    "AHPC",
    "AIL",
    "AKBSL",
    "AKJCL",
    "AKPL",
    "ALBSL",
    "ALICL",
    "ANLB",
    "API",
    "AVYAN",
    "BARUN",
    "BBC",
    "BFC",
    "BGWT",
    "BHDC",
    "BHL",
    "BHPL",
    "BNHC",
    "BNL",
    "BNT",
    "BOKL",
    "BPW",
    "CBBL",
    "CBL",
    "CCBL",
    "CFCL",
    "CHDC",
    "CHL",
    "CIT",
    "CITY",
    "CKHL",
    "CLI",
    "CORBL",
    "CYCL",
    "CZBIL",
    "DDBL",
    "DHPL",
    "DLBS",
    "DOLTI",
    "DORDI",
    "EBL",
    "EDBL",
    "EHPL",
    "EIC",
    "ENL",
    "FMDBL",
    "FOWAD",
    "GBBL",
    "GBIME",
    "GBLBS",
    "GCIL",
    "GFCL",
    "GHL",
    "GIC",
    "GILB",
    "GLBSL",
    "GLH",
    "GLICL",
    "GMFBS",
    "GMFIL",
    "GRDBL",
    "GUFL",
    "GVL",
    "HATHY",
    "HBL",
    "HDHPC",
    "HDL",
    "HEI",
    "HGI",
    "HHL",
    "HIDCL",
    "HLBSL",
    "HLI",
    "HPPL",
    "HRL",
    "HURJA",
    "ICFC",
    "IGI",
    "IHL",
    "ILBS",
    "ILI",
    "JALPA",
    "JBBL",
    "JBLB",
    "JFL",
    "JLI",
    "JSLBB",
    "KBL",
    "KBSH",
    "KDBY",
    "KDL",
    "KEF",
    "KKHC",
    "KLBSL",
    "KMCDB",
    "KPCL",
    "KRBL",
    "KSBBL",
    "LBBL",
    "LBL",
    "LEC",
    "LGIL",
    "LICN",
    "LLBS",
    "LSL",
    "LUK",
    "MAKAR",
    "MANDU",
    "MBJC",
    "MBL",
    "MCHL",
    "MDB",
    "MEGA",
    "MEHL",
    "MEL",
    "MEN",
    "MERO",
    "MFIL",
    "MHCL",
    "MHL",
    "MHNL",
    "MKCL",
    "MKHC",
    "MKHL",
    "MKJC",
    "MKLB",
    "MLBL",
    "MLBS",
    "MLBSL",
    "MMKJL",
    "MNBBL",
    "MPFL",
    "MSHL",
    "MSLB",
    "NABBC",
    "NABIL",
    "NADEP",
    "NBB",
    "NBL",
    "NCCB",
    "NESDO",
    "NFS",
    "NGPL",
    "NHDL",
    "NHPC",
    "NIB",
    "NICA",
    "NICL",
    "NICLBSL",
    "NIFRA",
    "NIL",
    "NIMB",
    "NLBBL",
    "NLG",
    "NLIC",
    "NLICL",
    "NMB",
    "NMBMF",
    "NMFBS",
    "NRIC",
    "NRM",
    "NRN",
    "NSLB",
    "NTC",
    "NUBL",
    "NWCL",
    "NYADI",
    "OHL",
    "PCBL",
    "PFL",
    "PHCL",
    "PIC",
    "PICL",
    "PLIC",
    "PMHPL",
    "PMLI",
    "PPL",
    "PRIN",
    "PROFL",
    "PRVU",
    "RADHI",
    "RAWA",
    "RBCL",
    "RFPL",
    "RHGCL",
    "RHPL",
    "RIDI",
    "RLFL",
    "RLI",
    "RMDC",
    "RNLI",
    "RRHP",
    "RULB",
    "RURU",
    "SABSL",
    "SADBL",
    "SAGF",
    "SAHAS",
    "SALICO",
    "SAMAJ",
    "SANIMA",
    "SAPDBL",
    "SARBTM",
    "SBCF",
    "SBI",
    "SBL",
    "SCB",
    "SDLBSL",
    "SFCL",
    "SFMF",
    "SGHC",
    "SGI",
    "SGIC",
    "SHEL",
    "SHINE",
    "SHIVM",
    "SHL",
    "SHLB",
    "SHPC",
    "SIC",
    "SICL",
    "SIFC",
    "SIKLES",
    "SIL",
    "SINDU",
    "SJCL",
    "SJLIC",
    "SKBBL",
    "SLBBL",
    "SLBSL",
    "SLCF",
    "SLI",
    "SLICL",
    "SLK",
    "SMATA",
    "SMB",
    "SMFBS",
    "SMFDB",
    "SMH",
    "SMHL",
    "SMJC",
    "SNLI",
    "SONA",
    "SPC",
    "SPDL",
    "SPHL",
    "SPL",
    "SRBL",
    "SRLI",
    "SSHL",
    "SSIS",
    "STC",
    "SWBBL",
    "SWMF",
    "TAMOR",
    "TPC",
    "TSHL",
    "TVCL",
    "UAIL",
    "UHEWA",
    "UIC",
    "ULBSL",
    "ULHC",
    "ULI",
    "UMHL",
    "UMRH",
    "UNHPL",
    "UNL",
    "UNLB",
    "UPCL",
    "UPPER",
    "USHEC",
    "USHL",
    "USLB",
    "VLBS",
    "VLUCL",
    "WNLB",
]

snp_500_symbols = [
    "AAPL",
    "MSFT",
    "NVDA",
    "GOOGL",
    "GOOG",
    "AMZN",
    "META",
    "LLY",
    "AVGO",
    "TSLA",
    "JPM",
    "WMT",
    "XOM",
    "UNH",
    "V",
    "MA",
    "PG",
    "JNJ",
    "ORCL",
    "COST",
    "HD",
    "ABBV",
    "BAC",
    "MRK",
    "CVX",
    "KO",
    "NFLX",
    "CRM",
    "ADBE",
    "PEP",
    "TMO",
    "AMD",
    "LIN",
    "WFC",
    "ACN",
    "TMUS",
    "QCOM",
    "DHR",
    "CSCO",
    "TXN",
    "GE",
    "ABT",
    "MCD",
    "AMGN",
    "INTU",
    "PM",
    "IBM",
    "AXP",
    "PFE",
    "BX",
    "CAT",
    "AMAT",
    "NOW",
    "MS",
    "VZ",
    "DIS",
    "GS",
    "ISRG",
    "CMCSA",
    "SPGI",
    "NEE",
    "RTX",
    "UNP",
    "T",
    "LOW",
    "UBER",
    "INTC",
    "HON",
    "COP",
    "VRTX",
    "BLK",
    "TJX",
    "SYK",
    "PGR",
    "BKNG",
    "LMT",
    "C",
    "ELV",
    "MU",
    "ETN",
    "SCHW",
    "LRCX",
    "REGN",
    "BA",
    "PLD",
    "ADI",
    "UPS",
    "BSX",
    "CB",
    "NKE",
    "MMC",
    "DE",
    "KLAC",
    "PANW",
    "KKR",
    "ADP",
    "BMY",
    "MDT",
    "ANET",
    "AMT",
    "CI",
    "GILD",
    "FI",
    "HCA",
    "ABNB",
    "SO",
    "MDLZ",
    "SHW",
    "MO",
    "ICE",
    "SBUX",
    "SNPS",
    "DUK",
    "ZTS",
    "MCO",
    "CL",
    "GD",
    "WM",
    "MCK",
    "CTAS",
    "APH",
    "CVS",
    "TT",
    "ITW",
    "FDX",
    "EQIX",
    "EOG",
    "CME",
    "PNC",
    "PH",
    "NOC",
    "USB",
    "CDNS",
    "MMM",
    "AON",
    "ECL",
    "SLB",
    "TDG",
    "TGT",
    "BDX",
    "CMG",
    "MAR",
    "CSX",
    "EMR",
    "MSI",
    "WELL",
    "ORLY",
    "FCX",
    "NXPI",
    "CRWD",
    "AJG",
    "PYPL",
    "MPC",
    "PSX",
    "CARR",
    "RSG",
    "TFC",
    "ROP",
    "APD",
    "DHI",
    "COF",
    "NSC",
    "CEG",
    "MET",
    "HLT",
    "NEM",
    "AFL",
    "OXY",
    "MNST",
    "CHTR",
    "PSA",
    "AZO",
    "VLO",
    "PCAR",
    "ADSK",
    "WMB",
    "AIG",
    "AEP",
    "O",
    "URI",
    "SRE",
    "SPG",
    "GM",
    "CPRT",
    "BK",
    "TRV",
    "LEN",
    "TEL",
    "OKE",
    "KMB",
    "GWW",
    "KMI",
    "GEV",
    "HUM",
    "DLR",
    "ROST",
    "MRNA",
    "CCI",
    "MCHP",
    "JCI",
]

nepali_banks = ["NABIL", "NIB", "NICA", "EBL", "GBIME"]
nepali_hydro = ["NHPC", "BPCL", "AHPC", "CHCL", "SHPC"]
nepali_microfinance = ["NMBMF", "CBBL", "DDBL", "SKBBL", "SWBBL"]
nepali_expensive = highest_price_tickers = ["UNL", "BNT", "RBCL", "STC", "BBC"]
floating_sensitive_stocks = ["SAMAJ", "SMH", "SPL", "KBSH", "BHPL"]

sectors_under_study = {
    "Banks": nepali_banks,
    "Hydro": nepali_hydro,
    "Microfinance": nepali_microfinance,
    "Expensive": nepali_expensive,
    "Low Floating": floating_sensitive_stocks,
}
pattern_with_names = {
    "CDLHAMMER": "Hammer",
    # "CDLINVERTEDHAMMER": "Inverted Hammer",
    # "CDLENGULFING": "Engulfing Pattern",
    # "CDLPIERCING": "Piercing Pattern",
    # "CDLMORNINGSTAR": "Morning Star",
    # "CDL3WHITESOLDIERS": "Three White Soldiers",
    # "CDLHARAMI": "Harami Pattern",
    # "CDLDRAGONFLYDOJI": "Dragonfly Doji",
    # "CDLDOJI": "Doji",
    # "CDLHANGINGMAN": "Hanging Man",
    # "CDLSHOOTINGSTAR": "Shooting Star",
    "CDLEVENINGSTAR": "Evening Star",
    # "CDL3BLACKCROWS": "Three Black Crows",
    # "CDLSPINNINGTOP": "Spinning Top",
    "CDLMARUBOZU": "Marubozu",
    # "CDLDARKCLOUDCOVER": "Dark Cloud Cover",
    # "CDLHARAMICROSS": "Harami Cross",
    # "CDL3INSIDE": "Three Inside Up-Down",
    # "CDL3OUTSIDE": "Three Outside Up-Down",
}

long_trends = ["Bullish", "Bearish"]
short_trends = ["yes", "no"]# basically means if there was a shortterm trend or not that is useful to test the effecacy of that candlestick theoritically
all_criteria =["Low/High", "Close"]
observation_durations_days =[2,4,8]


def get_short_trend(current_value, old_value):
    change_percentage = abs((current_value - old_value) / old_value) * 100
    if change_percentage < 5:
        return "Sideways"
    elif current_value > old_value:
        return "Up"
    else:
        return "Down"


patterns = [
    "CDLHAMMER",  # Hammer
    # "CDLINVERTEDHAMMER",  # Inverted Hammer
    # "CDLENGULFING",  # Engulfing Pattern
    # "CDLPIERCING",  # Piercing Pattern
    # "CDLMORNINGSTAR",  # Morning Star
    # "CDL3WHITESOLDIERS",  # Three White Soldiers
    # "CDLHARAMI",  # Harami Pattern
    # "CDLDRAGONFLYDOJI",  # Dragonfly Doji
    # "CDLDOJI",  # Doji
    # "CDLHANGINGMAN",  # Hanging Man
    # "CDLSHOOTINGSTAR",  # Shooting Star
    # "CDLEVENINGSTAR",  # Evening Star
    # "CDL3BLACKCROWS",  # Three Black Crows
    # "CDLSPINNINGTOP",  # Spinning Top
    # "CDLMARUBOZU",  # Marubozu
    # "CDLDARKCLOUDCOVER",  # Dark Cloud Cover
    # "CDLHARAMICROSS",  # Harami Cross
    # "CDL3INSIDE",  # Three Inside Up/Down
    # "CDLABANDONEDBABY",  # Abandoned Baby
    # "CDL3OUTSIDE",  # Three Outside Up/Down
]

us_data_path_crude = "/Users/laxmanbhattarai/Desktop/thesis_v2/data/step1_crude_data/us"
np_data_path_crude = "/Users/laxmanbhattarai/Desktop/thesis_v2/data/step1_crude_data/np"

us_data_path_normalized = (
    "/Users/laxmanbhattarai/Desktop/thesis_v2/data/step2_normalized_data/us"
)
np_data_path_normalized = (
    "/Users/laxmanbhattarai/Desktop/thesis_v2/data/step2_normalized_data/np"
)

us_data_path_candles = (
    "/Users/laxmanbhattarai/Desktop/thesis_v2/data/step3_candlesticks_data/us"
)
np_data_path_candles = (
    "/Users/laxmanbhattarai/Desktop/thesis_v2/data/step3_candlesticks_data/np"
)

data_path_transformed = (
    "/Users/laxmanbhattarai/Desktop/thesis_v2/data/step4_transformed_data"
)
