import os

current_directory = os.path.dirname(os.path.abspath(__file__)).split("src")[0]

# nepse_symbols_all = [
#     "ACLBSL",
#     "ADBL",
#     "AHL",
#     "AHPC",
#     "AIL",
#     "AKBSL",
#     "AKJCL",
#     "AKPL",
#     "ALBSL",
#     "ALICL",
#     "ANLB",
#     "API",
#     "AVYAN",
#     "BARUN",
#     "BBC",
#     "BFC",
#     "BGWT",
#     "BHDC",
#     "BHL",
#     "BHPL",
#     "BNHC",
#     "BNL",
#     "BNT",
#     "BOKL",
#     "BPW",
#     "CBBL",
#     "CBL",
#     "CCBL",
#     "CFCL",
#     "CHDC",
#     "CHL",
#     "CIT",
#     "CITY",
#     "CKHL",
#     "CLI",
#     "CORBL",
#     "CYCL",
#     "CZBIL",
#     "DDBL",
#     "DHPL",
#     "DLBS",
#     "DOLTI",
#     "DORDI",
#     "EBL",
#     "EDBL",
#     "EHPL",
#     "EIC",
#     "ENL",
#     "FMDBL",
#     "FOWAD",
#     "GBBL",
#     "GBIME",
#     "GBLBS",
#     "GCIL",
#     "GFCL",
#     "GHL",
#     "GIC",
#     "GILB",
#     "GLBSL",
#     "GLH",
#     "GLICL",
#     "GMFBS",
#     "GMFIL",
#     "GRDBL",
#     "GUFL",
#     "GVL",
#     "HATHY",
#     "HBL",
#     "HDHPC",
#     "HDL",
#     "HEI",
#     "HGI",
#     "HHL",
#     "HIDCL",
#     "HLBSL",
#     "HLI",
#     "HPPL",
#     "HRL",
#     "HURJA",
#     "ICFC",
#     "IGI",
#     "IHL",
#     "ILBS",
#     "ILI",
#     "JALPA",
#     "JBBL",
#     "JBLB",
#     "JFL",
#     "JLI",
#     "JSLBB",
#     "KBL",
#     "KBSH",
#     "KDBY",
#     "KDL",
#     "KEF",
#     "KKHC",
#     "KLBSL",
#     "KMCDB",
#     "KPCL",
#     "KRBL",
#     "KSBBL",
#     "LBBL",
#     "LBL",
#     "LEC",
#     "LGIL",
#     "LICN",
#     "LLBS",
#     "LSL",
#     "LUK",
#     "MAKAR",
#     "MANDU",
#     "MBJC",
#     "MBL",
#     "MCHL",
#     "MDB",
#     "MEGA",
#     "MEHL",
#     "MEL",
#     "MEN",
#     "MERO",
#     "MFIL",
#     "MHCL",
#     "MHL",
#     "MHNL",
#     "MKCL",
#     "MKHC",
#     "MKHL",
#     "MKJC",
#     "MKLB",
#     "MLBL",
#     "MLBS",
#     "MLBSL",
#     "MMKJL",
#     "MNBBL",
#     "MPFL",
#     "MSHL",
#     "MSLB",
#     "NABBC",
#     "NABIL",
#     "NADEP",
#     "NBB",
#     "NBL",
#     "NCCB",
#     "NESDO",
#     "NFS",
#     "NGPL",
#     "NHDL",
#     "NHPC",
#     "NIB",
#     "NICA",
#     "NICL",
#     "NICLBSL",
#     "NIFRA",
#     "NIL",
#     "NIMB",
#     "NLBBL",
#     "NLG",
#     "NLIC",
#     "NLICL",
#     "NMB",
#     "NMBMF",
#     "NMFBS",
#     "NRIC",
#     "NRM",
#     "NRN",
#     "NSLB",
#     "NTC",
#     "NUBL",
#     "NWCL",
#     "NYADI",
#     "OHL",
#     "PCBL",
#     "PFL",
#     "PHCL",
#     "PIC",
#     "PICL",
#     "PLIC",
#     "PMHPL",
#     "PMLI",
#     "PPL",
#     "PRIN",
#     "PROFL",
#     "PRVU",
#     "RADHI",
#     "RAWA",
#     "RBCL",
#     "RFPL",
#     "RHGCL",
#     "RHPL",
#     "RIDI",
#     "RLFL",
#     "RLI",
#     "RMDC",
#     "RNLI",
#     "RRHP",
#     "RULB",
#     "RURU",
#     "SABSL",
#     "SADBL",
#     "SAGF",
#     "SAHAS",
#     "SALICO",
#     "SAMAJ",
#     "SANIMA",
#     "SAPDBL",
#     "SARBTM",
#     "SBCF",
#     "SBI",
#     "SBL",
#     "SCB",
#     "SDLBSL",
#     "SFCL",
#     "SFMF",
#     "SGHC",
#     "SGI",
#     "SGIC",
#     "SHEL",
#     "SHINE",
#     "SHIVM",
#     "SHL",
#     "SHLB",
#     "SHPC",
#     "SIC",
#     "SICL",
#     "SIFC",
#     "SIKLES",
#     "SIL",
#     "SINDU",
#     "SJCL",
#     "SJLIC",
#     "SKBBL",
#     "SLBBL",
#     "SLBSL",
#     "SLCF",
#     "SLI",
#     "SLICL",
#     "SLK",
#     "SMATA",
#     "SMB",
#     "SMFBS",
#     "SMFDB",
#     "SMH",
#     "SMHL",
#     "SMJC",
#     "SNLI",
#     "SONA",
#     "SPC",
#     "SPDL",
#     "SPHL",
#     "SPL",
#     "SRBL",
#     "SRLI",
#     "SSHL",
#     "SSIS",
#     "STC",
#     "SWBBL",
#     "SWMF",
#     "TAMOR",
#     "TPC",
#     "TSHL",
#     "TVCL",
#     "UAIL",
#     "UHEWA",
#     "UIC",
#     "ULBSL",
#     "ULHC",
#     "ULI",
#     "UMHL",
#     "UMRH",
#     "UNHPL",
#     "UNL",
#     "UNLB",
#     "UPCL",
#     "UPPER",
#     "USHEC",
#     "USHL",
#     "USLB",
#     "VLBS",
#     "VLUCL",
#     "WNLB",
# ]

snp_500_symbols = [
    "AAPL",
    "MSFT",
    "NVDA",
    "GOOGL",
    "GOOG",
    "AMZN",
    "META",
    "LLY",
    "AVGO",
    "TSLA",
    "JPM",
    "WMT",
    "XOM",
    "UNH",
    "V",
    "MA",
    "PG",
    "JNJ",
    "ORCL",
    "COST",
    "HD",
    "ABBV",
    "BAC",
    "MRK",
    "CVX",
    "KO",
    "NFLX",
    "CRM",
    "ADBE",
    "PEP",
    "TMO",
    "AMD",
    "LIN",
    "WFC",
    "ACN",
    "TMUS",
    "QCOM",
    "DHR",
    "CSCO",
    "TXN",
    "GE",
    "ABT",
    "MCD",
    "AMGN",
    "INTU",
    "PM",
    "IBM",
    "AXP",
    "PFE",
    "BX",
    "CAT",
    "AMAT",
    "NOW",
    "MS",
    "VZ",
    "DIS",
    "GS",
    "ISRG",
    "CMCSA",
    "SPGI",
    "NEE",
    "RTX",
    "UNP",
    "T",
    "LOW",
    "UBER",
    "INTC",
    "HON",
    "COP",
    "VRTX",
    "BLK",
    "TJX",
    "SYK",
    "PGR",
    "BKNG",
    "LMT",
    "C",
    "ELV",
    "MU",
    "ETN",
    "SCHW",
    "LRCX",
    "REGN",
    "BA",
    "PLD",
    "ADI",
    "UPS",
    "BSX",
    "CB",
    "NKE",
    "MMC",
    "DE",
    "KLAC",
    "PANW",
    "KKR",
    "ADP",
    "BMY",
    "MDT",
    "ANET",
    "AMT",
    "CI",
    "GILD",
    "FI",
    "HCA",
    "ABNB",
    "SO",
    "MDLZ",
    "SHW",
    "MO",
    "ICE",
    "SBUX",
    "SNPS",
    "DUK",
    "ZTS",
    "MCO",
    "CL",
    "GD",
    "WM",
    "MCK",
    "CTAS",
    "APH",
    "CVS",
    "TT",
    "ITW",
    "FDX",
    "EQIX",
    "EOG",
    "CME",
    "PNC",
    "PH",
    "NOC",
    "USB",
    "CDNS",
    "MMM",
    "AON",
    "ECL",
    "SLB",
    "TDG",
    "TGT",
    "BDX",
    "CMG",
    "MAR",
    "CSX",
    "EMR",
    "MSI",
    "WELL",
    "ORLY",
    "FCX",
    "NXPI",
    "CRWD",
    "AJG",
    "PYPL",
    "MPC",
    "PSX",
    "CARR",
    "RSG",
    "TFC",
    "ROP",
    "APD",
    "DHI",
    "COF",
    "NSC",
    "CEG",
    "MET",
    "HLT",
    "NEM",
    "AFL",
    "OXY",
    "MNST",
    "CHTR",
    "PSA",
    "AZO",
    "VLO",
    "PCAR",
    "ADSK",
    "WMB",
    "AIG",
    "AEP",
    "O",
    "URI",
    "SRE",
    "SPG",
    "GM",
    "CPRT",
    "BK",
    "TRV",
    "LEN",
    "TEL",
    "OKE",
    "KMB",
    "GWW",
    "KMI",
    "GEV",
    "HUM",
    "DLR",
    "ROST",
    "MRNA",
    "CCI",
    "MCHP",
    "JCI",
]
nepali_banks = {
    "NABIL": "Nabil Bank Limited",
    "NICA": "NIC Asia Bank Limited",
    "SCB": "Standard Chartered Bank Nepal",
    "HBL": "Himalayan Bank Limited",
    "EBL": "Everest Bank Limited",
    "GBIME": "Global IME Bank Limited",
    "MBL": "Machhapuchchhre Bank Limited",
    "SBL": "Siddhartha Bank Limited",
    "PRVU": "Prabhu Bank Limited",
    "CZBIL": "Citizens Bank International Limited",
    "LBL": "Laxmi Bank Limited",
    "ADBL": "Agriculture Development Bank Limited",
    "SBI": "State Bank of India Nepal",
    "SANIMA": "Sanima Bank Limited",
    "KBL": "Kumari Bank Limited",
}
nepali_hydro = {
    "NHPC": "National Hydropower Company Ltd.",
    "UPPER": "Upper Tamakoshi Hydropower Ltd.",
    "AHPC": "Arun Valley Hydropower Development Co. Ltd.",
    "API": "API Power Company Ltd.",
    "SHPC": "Sanima Mai Hydropower Ltd.",
    "NGPL": "Ngadi Group Power Ltd.",
    "HPPL": "Himalayan Power Partner Ltd.",
    "SIKLES": "Sikles Hydropower Ltd.",
    "RADHI": "Radhi Bidyut Company Ltd.",
    "AKJCL": "Ankhukhola Hydropower Ltd.",
    "MKHC": "Mailung Khola Hydropower Ltd.",
    "BARUN": "Barun Hydropower Company Ltd.",
    "TVCL": "Trishuli Jal Vidhyut (Hydropower)",
    "USHL": "Upper Syange Hydropower",
    "KBSH": "Kutheli Bukhari Small Hydropower",
    "SPL": "Shuvam Power Limited",
}
nepali_microfinance = {
    "NMBMF": "NMB Microfinance Bittiya Sanstha Ltd.",
    "CBBL": "Chhimek Laghubitta Bittiya Sanstha Ltd.",
    "DDBL": "Deprosc Laghubitta Bittiya Sanstha Ltd.",
    "SKBBL": "Sana Kisan Bikas Bank Ltd.",
    "SWBBL": "Swabalamban Laghubitta Bittiya Sanstha Ltd.",
    "GRDBL": "Grameen Bikas Laghubitta Ltd.",
    "NUBL": "Nerude Laghubitta Bittiya Sanstha Ltd.",
    "MLBS": "Manakamana Laghubitta Bittiya Sanstha Ltd.",
    "FOWAD": "Forward Microfinance Laghubitta Ltd.",
    "SADBL": "Siddhartha Laghubitta Bittiya Sanstha Ltd.",
    "MERO": "Mero Microfinance Bittiya Sanstha Ltd.",
    "KMCDB": "Kalika Microcredit Development Bank Ltd.",
    "SLBBL": "Samudayik Laghubitta Bittiya Sanstha Ltd.",
    "MLBSL": "Mahila Laghubitta Bittiya Sanstha Ltd.",
    "JALPA": "Jalpa Samudayik Laghubitta Bittiya Sanstha Ltd.",
}
nepali_expensive = {
    "UNL": "Unilever Nepal Ltd (Consumer Goods)",
    "RBCL": "Rastriya Beema Company Ltd (Insurance)",
    "BNT": "Bottlers Nepal (Terai) Ltd (Beverages)",
    "STC": "Salt Trading Corporation (Trading)",
    "BBC": "Bishal Bazar Company Ltd (Retail)",
    "NLIC": "Nepal Life Insurance Co. Ltd (Insurance)",
    "NLICL": "National Life Insurance Co. Ltd (Insurance)",
    "SHIVM": "Shivam Cements Ltd (Manufacturing)",
    "NRIC": "Nepal Reinsurance Company Ltd (Insurance)",
    "SHL": "Soaltee Hotel Ltd (Tourism/Hospitality)",
    "NTC": "Nepal Telecom (Telecom)",
    "SICL": "Shikhar Insurance Co. Ltd (Insurance)",
    "BNL": "Bottlers Nepal (Balaju) Ltd (Beverages)",
    "ANLB": "Aatmanirbhar Laghubitta (Microfinance)",
    "MLBSL": "Mahila Laghubitta Bittiya Sanstha (Microfinance)",
}
floating_sensitive_stocks = {
    "SAMAJ": "Samaj Laghubitta (Microfinance, Paid-up: ₹2.28 crore)",
    "SMH": "Supermai Hydropower (Hydropower, Price: ~₹643)",
    "SPL": "Shuvam Power Limited (Hydropower, Paid-up: ₹20 crore)",
    "KBSH": "Kutheli Bukhari Small Hydropower (Hydropower, Paid-up: ₹12.18 crore)",
    "BHPL": "Barahi Hydropower (Hydropower, Paid-up: ₹25 crore)",
    "ANLB": "Aatmanirbhar Laghubitta (Microfinance, Paid-up: ₹6.85 crore)",
    "WNLB": "Wean Nepal Laghubitta (Microfinance, Paid-up: ₹7.92 crore)",
    "DLBS": "Dhaulagiri Laghubitta (Microfinance, Paid-up: ₹10.31 crore)",
    "SMB": "Support Laghubitta (Microfinance, Paid-up: ₹10.76 crore)",
    "MLBS": "Manushi Laghubitta (Microfinance, Paid-up: ₹10.93 crore)",
    "SHLB": "Shrijanshil Laghubitta (Microfinance, Paid-up: ₹10.93 crore)",
    "SMFBS": "Swabhimaan Laghubitta (Microfinance, Paid-up: ₹14.61 crore)",
    "UNLB": "Unique Nepal Laghubitta (Microfinance, Paid-up: ₹14.85 crore)",
    "GMFBS": "Ganapati Laghubitta (Microfinance, Paid-up: ₹15.15 crore)",
    "JSLBB": "Janautthan Samudayic Laghubitta (Microfinance, Paid-up: ₹17 crore)",
}

sectors_under_study = {
    "Banks": nepali_banks,
    "Hydro": nepali_hydro,
    "Microfinance": nepali_microfinance,
    "Expensive": nepali_expensive,
    "Low Floating": floating_sensitive_stocks,
}

nepse_symbols = (
    list(nepali_banks.keys())
    + list(nepali_hydro.keys())
    + list(nepali_microfinance.keys())
    + list(nepali_expensive.keys())
    + list(floating_sensitive_stocks.keys())
)
pattern_with_names = {
    "CDLHAMMER": "Hammer",
    "CDLINVERTEDHAMMER": "Inverted Hammer",
    "random": "Random",
    # "CDLENGULFING": "Engulfing Pattern",
    # "CDLPIERCING": "Piercing Pattern",
    # "CDLMORNINGSTAR": "Morning Star",
    # "CDL3WHITESOLDIERS": "Three White Soldiers",
    # "CDLHARAMI": "Harami Pattern",
    # "CDLDRAGONFLYDOJI": "Dragonfly Doji",
    # "CDLDOJI": "Doji",
    "CDLHANGINGMAN": "Hanging Man",
    "CDLSHOOTINGSTAR": "Shooting Star",
    # "CDLBULLISHENGULFING": "Bullish Engulfing",
    # "CDLEVENINGSTAR": "Evening Star",
    # "CDL3BLACKCROWS": "Three Black Crows",
    # "CDLSPINNINGTOP": "Spinning Top",
    # "CDLMARUBOZU": "Marubozu",
    # "CDLDARKCLOUDCOVER": "Dark Cloud Cover",
    # "CDLHARAMICROSS": "Harami Cross",
    # "CDL3INSIDE": "Three Inside Up-Down",
    # "CDL3OUTSIDE": "Three Outside Up-Down",
}

long_trends = ["Bullish", "Bearish"]
short_trends = [
    "yes",
    "no",
]  # basically means if there was a shortterm trend or not that is useful to test the effecacy of that candlestick theoritically
all_criteria = ["Low", "High", "Close"]
durations = [2, 4, 8]


def get_short_trend(current_value, old_value):
    change_percentage = abs((current_value - old_value) / old_value) * 100
    if change_percentage < 5:
        return "Sideways"
    elif current_value > old_value:
        return "Up"
    else:
        return "Down"


patterns = [
    "CDLHAMMER",  # Hammer
    # "CDLINVERTEDHAMMER",  # Inverted Hammer
    # "CDLENGULFING",  # Engulfing Pattern
    # "CDLPIERCING",  # Piercing Pattern
    # "CDLMORNINGSTAR",  # Morning Star
    # "CDL3WHITESOLDIERS",  # Three White Soldiers
    # "CDLHARAMI",  # Harami Pattern
    # "CDLDRAGONFLYDOJI",  # Dragonfly Doji
    # "CDLDOJI",  # Doji
    # "CDLHANGINGMAN",  # Hanging Man
    # "CDLSHOOTINGSTAR",  # Shooting Star
    # "CDLEVENINGSTAR",  # Evening Star
    # "CDL3BLACKCROWS",  # Three Black Crows
    # "CDLSPINNINGTOP",  # Spinning Top
    # "CDLMARUBOZU",  # Marubozu
    # "CDLDARKCLOUDCOVER",  # Dark Cloud Cover
    # "CDLHARAMICROSS",  # Harami Cross
    # "CDL3INSIDE",  # Three Inside Up/Down
    # "CDLABANDONEDBABY",  # Abandoned Baby
    # "CDL3OUTSIDE",  # Three Outside Up/Down
]

us_data_path_crude = f"{current_directory}data/step1_crude_data/us"
np_data_path_crude = f"{current_directory}data/step1_crude_data/np"

us_data_path_normalized = f"{current_directory}data/step2_normalized_data/us"
np_data_path_normalized = f"{current_directory}data/step2_normalized_data/np"

us_data_path_candles = f"{current_directory}data/step3_candlesticks_data/us"
np_data_path_candles = f"{current_directory}data/step3_candlesticks_data/np"

np_data_path_descriptive_stats = f"{current_directory}data/step4_descriptive_stats/np"
us_data_path_descriptive_stats = f"{current_directory}data/step4_descriptive_stats/us"

data_path_transformed = f"{current_directory}data/step4_transformed_data"
